@LearningJwt.Api_HostAddress = https://localhost:7250

GET {{LearningJwt.Api_HostAddress}}/weatherforecast/
Accept: application/json
kid: 9dfd3aec-12ee-4c81-9f33-86bff48194ed
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjlkZmQzYWVjLTEyZWUtNGM4MS05ZjMzLTg2YmZmNDgxOTRlZCIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlciIsImp0aSI6Ijk0ODI1YWM5LTE2MmYtNGRiZS05YTc4LTgxMTc1MDljNGJkMSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJuYmYiOjE3NTEwNjYyMTUsImV4cCI6MTc1MTA2ODAxNSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI1MCIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcyNTAifQ.TD_eIjlap_FMxUUwd29TZ1ML_kfYqHHvmMhgz4T1_Hnl5dTFcM5HkNZ1cye2zRrMR3wSSbQ9ddEqblEPsdc9XxIUPtLSAvS6Lt7KR9IjAKrx-X5U8AmgXKbM8lUjy49ssSPF0E8sapFCYgh6UO2JMylDkiNOGgA1uOjZz18PYxqmd1-nGvLezx4SMNwwr-BwNHJjWuGS9kcaqAmuqqZ2MBltdu9BlC7gDoUghEIpnYa16ILDqJ0YRbwMcE7BdL7nQMyViBlSiCvCvRBqlFDpzkH1H9AZq4ZraPzK3Im1NPyaIM8z8zQo6ev8uYwNUQfL-BP9BsLYIT5dbwXlY_bdTw

###

POST {{LearningJwt.Api_HostAddress}}/accounts/login
Content-Type: application/json

{
  "username": "user",
  "password": "user123"
}    